### ISSUE TITLE
Solving piecewise or boolean expressions

### ISSUE THREAD

**Issue by jarble** [wbhart/Nemo.jl#105]
I'm not sure if Nemo is able to solve piecewise functions or boolean expressions, since its documentation doesn't mention them. It's possible to solve some boolean or piecewise expressions by [converting them into equations](https://stackoverflow.com/questions/40872875/solving-constraint-satisfaction-problems-in-sympy), but they would need to written in conjunctive normal form first.

For example, it would be possible to solve `((a=1) or (a=2)) and (a=b+1)` by re-writing it as a system of equations, like `(a-1)*(a-2) = 0, a=b+1`. Is Nemo already able to do this?

**Comment by wbhart** [comment]
I don't believe we can do this at present. It might be possible to solve equations like this in Singular, but it's not my area, so I'm not really sure.

We essentially only have linear solving in Nemo.

**Comment by jarble** [comment]
Essentially, I only need to solve systems of polynomial equations here, since some simple boolean formulas can be written in this way. Is Nemo able to solve systems of polynomial equations?

**Comment by wbhart** [comment]
No, I don't think we can do that. There might be something you can do using our resultant function, which is pretty reasonable in performance. But otherwise I think you need something like Groebner bases. I'll ask around and see if anyone who knows what they are talking about, can help you.

The reason no one else is replying here is that this is my private GitHub repo, not the main repo, which is at Nemocas rather than wbhart. You might like to open the ticket over there.

**Comment by wbhart** [comment]
Apparently the Polybori component of Singular should be able to do this for boolean expressions at least. But I've written to one of my colleagues who is currently on secondment to see if he can say something more precise.

**Comment by ederc** [comment]
The PolyBori C++ library might be the way to go: It solves boolean systems of equations. It has an interface to Singular, see https://www.singular.uni-kl.de/Manual/latest/sing_2317.htm#IDX949. Moreover, you can also call it via Sage (whereas I do not know the status of this interface, since there is no current development on PolyBori).
