### ISSUE TITLE
Compatibility with MultivariatePolynomials

### ISSUE THREAD

**Issue by blegat** [wbhart/Nemo.jl#69]
We have created a package [MultivariatePolynomials](https://github.com/blegat/MultivariatePolynomials.jl) for efficient operations with multivariate polynomials.
It seems to be rather complementary to Nemo since it is designed for handling coefficients of any type (no assumption at all is made on the coefficient type) while Nemo is designed for very efficient implementation of specific types.
Your type `GenPoly` seems very similar to our type `VecPolynomial`.
It would be very beneficial if there was a sort of compatibility between Nemo and MultivariatePolynomials.

For instance, if Nemo was split in 2 packages: one defining all the abstract types and one defining the efficient implementations with all the library dependencies then MultivariatePolynomials could use these abstract types and share the `GenPoly` type without needing to add all the library dependencies.

One issue though is that you define `GenPoly{T <: RingElem}` where MultivariatePolynomials lets `T` be anything... One way to fix this is to add the `RingElem` type in Julia Base and use it as a parent for all types of the ecosystem that fits ^^

**Comment by wbhart** [comment]
Thanks for pointing out your project which looks very nice.

We have also been working very hard on multivariate polynomials, both
generically in Julia [1] and specifically in Flint [2]. Of course much
remains to be done, but we are already getting timings that are hundreds of
times faster than what we have had in the past.

It's not true that Nemo is for specific types only. There is a generics
system in Nemo, which we plan to extend radically over the next few years.
It is true that at the moment, we only support constructing generic
polynomials over a (commutative) ring. We don't yet support constructing
polynomials over anything.

We plan to introduce some types such as JuliaInt <: RingElem, which would
allow using Julia Ints as a coefficient ring for Nemo polynomials. This
would be implemented as an immutable type wrapping a Julia Int.

I'm skeptical that adding the RingElem and Ring abstract types to Julia
Base is the right thing to do. There are rather a lot of these. See
AbstractTypes.jl in Nemo.jl. And I just added another few the other day.
There are going to be many, many more in future.

I take your point about the abstract types in Nemo not being available
without the rather heavyweight library dependencies, which is not ideal for
applications such as yours. (By the way, we are currently planning to
remove Pari/GP as a dependency in Nemo.)

We have thought about moving these abstract types out into a separate
package before now, for precisely this reason. One thing that makes me
hesitate to do that is that it's really a hack to work around a limitation
in Julia itself. The same is true of introducing a JuliaInt <: RingElem
type. The latter is a hack to work around the lack of multiple inheritance.
The former is due to the special nature of abstract types and their role in
Julia.

One thing which will alleviate the use of Nemo for other packages is that
we plan to use Conda.jl to supply binaries for the library dependencies.
Probably that wont be enough for light weight packages that simply don't
want to require Nemo.

Obviously we do need to do something to fix the problem you've identified.
But I'd like to explore all possible solutions.

One thing that isn't clear just yet is if we will need to make RingElem and
the type parameterised. For example, what happens if you implement an
algorithm in MultivariatePolynomials which only works for other
MultivariatePolynomials types. How do you specify that you want a type that
is both a MultivariatePolynomials type and a member of RingElem?

If RingElem were parameterised, you could specify T <:
RingElem{:multivariatepolynomials}. We've already hit this issue, for
example in Singular.jl [3].

Many of the algorithms there only work over Singular polynomial rings.
Currently the SingularIdeal constructor for example, really wants to take T
<: RingElem{:singular}.

Anyway, thanks for bringing this topic up. I'd like to discuss all the
possibilities and to try and get some idea of which direction Julia itself
is going to head on this issue. Obviously moving abstract types into Base
isn't a scalable solution to issues like this. Nor is every package having
a separate abstract types package. So I feel that it's a general problem
that needs a rather general solution.

Bill.

[1] https://github.com/wbhart/Nemo.jl/tree/mpoly/src/generic
[2] https://github.com/wbhart/flint2/tree/fmpz_mpoly/fmpz_mpoly
[3] https://github.com/wbhart/Singular.jl

**Comment by blegat** [comment]
Thanks for your quick reply. Of course, moving the abstract type to Base is not a solution.

I am not sure to understand what you mean by:
"We have thought about moving these abstract types out into a separate package before now, for precisely this reason. One thing that makes me hesitate to do that is that it's really a hack to work around a limitation in Julia itself. (...) The former is due to the special nature of abstract types and their role in Julia."
Why would it be a hack to split it in separate packages ?

I also do not understand what you mean by "MultivariatePolynomials' type". The type we are talking about is the type of the coefficients of the polynomial, isn't it ? Those can just be anything as long as addition, ... are defined for MultivariatePolynomials.
This confusion might be due to my bad understanding of how Nemo work. For instance, how would the polynomial `2x + 3x^2*y` be represented using `GenPoly` ? In view of the following:
```julia
type GenPolyRing{T <: RingElem} <: PolyRing{T}
   base_ring::Ring
   S::Symbol
end
type GenPoly{T <: RingElem} <: PolyElem{T}
   coeffs::Array{T, 1}
   length::Int
   parent::GenPolyRing{T}
end
```
I would say that `length` is 2, `T` `Int` (or `JuliaInt`) and `coeffs` is `[2, 3]` but where are the corresponding monomials stored ?

**Comment by wbhart** [comment]
On 16 December 2016 at 14:46, Benoît Legat <notifications@github.com> wrote:

> Thanks for your quick reply. Of course, moving the abstract type to Base
> is not a solution.
>
> I am not sure to understand what you mean by:
> "We have thought about moving these abstract types out into a separate
> package before now, for precisely this reason. One thing that makes me
> hesitate to do that is that it's really a hack to work around a limitation
> in Julia itself. (...) The former is due to the special nature of abstract
> types and their role in Julia."
> Why would it be a hack to split it in separate packages ?
>

It's a hack because every time this sort of issue arises, package
maintainers are going to have to split their packages into two (artificial)
packages. If Julia ever comes up with a more general solution to this
problem, the hack will no longer be needed. I mean, let's face it, there is
no other reason to split Nemo into two packages right now. We would only be
doing it because of the abstract type issue that you've mentioned.

> I also do not understand what you mean by "MultivariatePolynomials' type".
> The type we are talking about is the type of the coefficients of the
> polynomial, isn't it ? Those can just be anything as long as addition, ...
> are defined for MultivariatePolynomials.
>
Do your multivariate polynomials really work for things that are not
commutative rings? For example, do they work over noncommutative rings? Do
they work over nonassociative algebras?

What other kinds of objects do your MultivariatePolynomials work over?

The real issue for us is that many algorithms are different if they are
over noncommutative or nonassociative rings, fields, commutative rings,
integral domains, etc. So we can't just put T and let it be anything, since
the algorithms have to be very different in those other cases, some more
general, some less general than commutative rings. (By the way, Nemo.Ring
is currently exclusively commutative rings; we will later add a
Nemo.CommRing abstract type and distinguish the noncommutative case from
the commutative case.)

> This confusion might be due to my bad understanding of how Nemo work. For
> instance, how would the polynomial 2x + 3x^2*y be represented using
> GenPoly ? In view of the following:
>
> type GenPolyRing{T <: RingElem} <: PolyRing{T}
>    base_ring::Ring
>    S::Symbolendtype GenPoly{T <: RingElem} <: PolyElem{T}
>    coeffs::Array{T, 1}
>    length::Int
>    parent::GenPolyRing{T}end
>
> I would say that length is 2, T Int (or JuliaInt) and coeffs is [2, 3]
> but where are the corresponding monomials stored ?
>

GenPoly is for univariate polynomials, not multivariate polynomials. You
can look at the MPoly.jl file at the link I gave you to see how we are
handling generic polynomials. We store multivariate polynomials in sparse
distributed format. Again, we currently make the assumption that all our
rings are commutative. Later on we'll rectify this.

Bill.

**Comment by wbhart** [comment]
I should also mention that currently we couldn't trivially remove the
dependency of Nemo on Flint (which has in turn a dependency in GMP and
MPFR). For example, our generic matrices need a permutation type, which
because we are lazy, we got from Flint.

It's possible there is an efficient Julia permutation type we could use
instead, but currently that means doing some work to fix that.

Also, Nemo can't be tested without some "leaf" rings, which are currently
provided by Flint. We could test the Nemo generics using some Julia types
if we could make them belong to Nemo.Ring. That can only happen currently
if we wrap the Julia types and make the wrapper types belong to Nemo.Ring.

I've been leaving that decision as long as possible, so that I can try to
get a handle on how the Julia developers intend to handle multiple
inheritance. It seems that some form of traits might become available
eventually. It's unclear whether this will be all we need or not. Maybe
it's enough, but we need to see what actually gets developed, and what
restrictions there are before we can really decide this.

Bill.

**Comment by blegat** [comment]
Thanks a lot for this complementary information, it helps to see what the long terms plans of Nemo.
To answer your question, the type of the parameters is currently not assumed to be commutative (for example, you could have `VecPolynomial{Matrix{Int}}`) even if I have not tested that so much. However, the variables are assumed to be commutative (`x*y*x = x^2*y`).
The purpose of `MultivariatePolynomials` is more to give a very userfriendly interface for creating polynomials by multiplying, adding, substracting, ... variables defined using the `@polyvar` macro. The type of the coefficients is automatically determined using promotion.
The goal would be that when the user wants to do something more involved (such as groebner basis computation), then MultivariatePolynomials would hands over to Nemo :-P
For this goal, it is good to see that Nemo also provide generic implementation for common operations (e.g. in [generic/MPoly.jl](https://github.com/wbhart/Nemo.jl/blob/mpoly/src/generic/MPoly.jl)).

The issue with commutativity that makes the algorithm so different is the commutativity of the coefficients (e.g. `Matrix{Int}`) or the commutativity of the variables ?

**Comment by wbhart** [comment]
On 16 December 2016 at 16:22, Benoît Legat <notifications@github.com> wrote:

> Thanks a lot for this complementary information, it helps to see what the
> long terms plans of Nemo.
> To answer your question, the type of the parameters is currently not
> assumed to be commutative (for example, you could have
> VecPolynomial{Matrix{Int}}) even if I have not tested that so much.
> However, the variables are assumed to be commutative (x*y*x = x^2*y).
> The purpose of MultivariatePolynomials is more to give a very
> userfriendly interface for creating polynomials by multiplying, adding,
> substracting, ... variables defined using the @polyvar macro. The type of
> the coefficients is automatically determined using promotion.
> The goal would be that when the user wants to do something more involved
> (such as groebner basis computation), then MultivariatePolynomials would
> hands over to Nemo :-P
> For this goal, it is good to see that Nemo also provide generic
> implementation for common operations (e.g. in generic/MPoly.jl
> <https://github.com/wbhart/Nemo.jl/blob/mpoly/src/generic/MPoly.jl>).
>
> The issue with commutativity that makes the algorithm so different is the
> commutativity of the coefficients (e.g. Matrix{Int}) or the commutativity
> of the variables ?
>

The algorithms for noncommutative coefficients have to be done quite
carefully. I don't think our current multiplication or powering algorithms
would work for noncommuting coefficients.

For example, if you multiply a polynomial f by itself, the algorithm might
call a special squaring algorithm which only works for a commutative ring.
You can't do that in the noncommutative setting obviously.

Some algorithms, such as multiplication, probably just need careful
checking to work in the noncommutative case. But powering needs to be
implemented differently I would expect. And things like gcd might not even
be meaningful.

We also assume the variables commute for polynomials in Nemo. But I think
they are not called polynomials if they don't. I can't recall what name is
used. Free associate algebra or something like that. We'll implement that
quite separately. (It can be simulated using ordinary polynomial
operations, by introducing additional variables.)

Bill.

**Comment by wbhart** [comment]
Sorry, there was a typo there: I meant "Free associative algebra" not "Free
associate algebra" of course.

**Comment by wbhart** [comment]
As a simple example of the commutative vs noncommutative coefficients,
imagine computing (ax + b)^2 in R[x] where a and b are coefficients in the
noncommutative ring R.

You have to compute a^2x^2 + abx + bax + b^2 in the noncommutative case,
but in the commutative case you can simply compute a^2x^2 + 2abx + b^2,
which can obviously be computed more efficiently if multiplication by 2 is
cheaper than element multiplication in R.

Bill.

**Comment by blegat** [comment]
I see. Then would the following work ? :

* If `T` is some unrecognized type, we assume it is noncommutative and we do not apply "shortcut" such as the power algorithms you were mentioning and we do not define the GCD.
* If `T` is recognized (e.g. it is an `Int` or a `BigInt`) then we use the future multiple inheritance that will eventually appear to say that they are subtypes of `CommRingElem`. 

With this, everything can work magically using Multiple dispatch. For instance
```julia
type GenMPoly{T<:Any}
...
end
+(::GenMPoly, ::GenMPoly) # works if T is noncommutative
*(::GenMPoly, ::GenMPoly) # works if T is noncommutative
^{T<:CommRingElem}(::GenMPoly{T}, ::GenMPoly{T}) # shortcut if T is commutative, otherwise, Base.^ is called which use *(::GenMPoly, ::GenMPoly)
someoperation(::GenMPoly{BigInt}, ::GenMPoly{BigInt}) # use faster library for that specific type
```
With this, the GenMPoly type can be shared between MultivariatePolynomials and Nemo and that would give a easy to use interface to build Nemo polynomials.

Before multiple inheritance, we will need to use `JuliaInt` and do the casting at some point...

**Comment by wbhart** [comment]
We can't define polynomials over T <: Any. Sometimes that doesn't even make
sense, and if T is not associative even the generic algorithms you have in
mind won't work.

The best we can do is define Nemo MPolys over Nemo.Ring and have special
algorithms over Nemo.CommRing and Nemo.Field, etc., where they are
available.

Rewriting Nemo to deal with the generic noncommutative case is clearly the
way to go, but it will still be MPoly{T} for T <: Nemo.Ring, not T <: Any,
which doesn't make sense.

Multiple inheritance is only needed for Julia types like Int, at the
moment, not for distinguishing the commutative and noncommutative cases
(though it would be useful to be able to distinguish exact rings from
numerical and other inexact rings, e.g. padics and power series).

Bill.

**Comment by wbhart** [comment]
Sorry, more typos. I of course mean T <: Nemo.RingElem, not T <: Nemo.Ring,
etc.

**Comment by wbhart** [comment]
A couple of us had a discussion about this issue, and here is what I
currently think as a result of the discussion. This is just what I think is
the Right Thing TM; there aren't necessarily people jumping up with their
hands in the air volunteering to actually do all the coding for it.

* Nemo currently consists of a generics layer and a wrapper of
GMP/MPFR/Flint/Arb/Antic/Pari. (Though we currently intend to remove Pari
as a dependency of Nemo.) So this is a natural line along which Nemo could
be split. An interesting question is which part should continue to be
called Nemo.jl. Probably the generic Julia code should be called Nemo.jl
and the wrappers of various libraries should be called Flint.jl (say).

* In order to separate Flint.jl (containing the GMP/MPFR/Arb/Flint/Antic
wrappers) we need to develop a Julia permutations module to replace the
Flint one. We'd also have to move all the functions that currently use the
Flint integers out of the generic code and into the Flint.jl module.

* We'd need to wrap Julia Int, Rational{Int}, BigInt and Rational{BigInt}
types and make the wrapper types belong to Nemo.RingElem and Nemo.FieldElem.

* We'd have to reimplement all our unsafe operators (currently mul!,
addeq!, zero! and add!) to return the mutated values, so that they can also
be used with immutable types. We'd then have to replace all the calls to
such operators with the new variants.

* The advantage for us pf splitting Nemo.jl would be reduced precompilation
time. If a change is made in Flint.jl it wouldn't require a precompilation
of Nemo.jl and vice versa. This would speed up development time for us.

* The advantage for other Julia packages is they could use Nemo.jl generics
without having to include Flint.jl with all the C library dependencies.

Even after all this, however, there are two things you should be aware of:

* Nemo generics do not currently work with Julia types, because the types
need to belong to Nemo.RingElem or Nemo.FieldElem etc, and because Nemo
requires the unsafe operators (currently mul!, addeq!, zero! and add!) to
be provided for the types, parents to be provided and a number of other
functions (elem_type, parent_type, base_ring, is_negative, show_minus_one,
needs_parentheses, hash, deepcopy, zero, one, iszero, isone, isunit, and
sometimes canonical_unit, and a bunch of other things) in order to work. So
the generics are not designed to work with just any arbitrary type. There
is a whole interface they need to support.

* Currently, all rings in Nemo are assumed to be commutative. You code
could work with Nemo types happily without changing it, because you only
require T <: Any. But the types you provide would not want to belong to
Nemo.RingElem because this currently implies they are commutative, and as
you have said, your code doesn't assume commutativity. And if the base ring
of a polynomial ring is noncommutative then so are the polynomials over it.
So currently, you don't want MultivariatePolynomials to belong to
Nemo.RingElem but to Any, which they already do.

So even if we made all the above changes, it probably still wouldn't give
you anything you don't already have, i.e. not necessarily commutative
polynomials over not necessarily commutative rings.

I think it is moderately likely that we will eventually move towards doing
all the above. But it's going to take time, perhaps a year or more.

Bill.

**Comment by wbhart** [comment]
There's an additional point I forgot to add:

* We'd eventually like CommRingElem <: RingElem <: Any, to distinguish the
commutative and noncommutative cases. But then we'd like
GenMPoly{CommRingElem} <: CommRingElem and GenMPoly{RingElem} <: RingElem.
But this kind of thing isn't currently possible in Julia. This makes me
think that in the long run, things like commutative/noncommutative,
associative/nonassociative and exact/nonexact, will be traits and that the
only abstract types we will have will be FieldElem <: RingElem.

Another example of this is SkewFieldElem, where you want both FieldElem <:
SkewFieldElem and FieldElem <: CommRingElem. This isn't currently possible
in Julia, and again is probably going to require traits to make it work.

Until traits exist in Julia, I think we are just going to have:

        CommRingElem <: RingElem <: GroupElem <: SetElem
                                                                          /
      ModuleElem{T <: CommRingElem} <:

This covers commutative algebra pretty well and will probably serve us ok
for the first year or two (there might be other things like resolutions,
sheaves and so on, of course).

Bill.

**Comment by blegat** [comment]
Thanks a lot for this detailed clarification!


> We can't define polynomials over T <: Any. Sometimes that doesn't even make sense, and if T is not associative even the generic algorithms you have in mind won't work.

Indeed, allowing any T might lead to cases that do not make sense but when writing generic algorithms/libraries, we kind of need to take those risks. If the user provide a T that is not a Ring, he will be responsible :-P Of course, since you need it to implement the unsafe operation (I saw [your post](https://groups.google.com/forum/#!topic/julia-dev/uqp7LziUEfY) on google groups explaining that you needed this to avoid to many allocations with BigInt (By the way, this post helped me a lot last year when needed to reimplement mpz et mpq wrappers for [CDDLib](https://github.com/JuliaPolyhedra/CDDLib.jl/blob/master/src/mytype.jl) and [LRSLib](https://github.com/JuliaPolyhedra/LRSLib.jl/blob/master/src/lrstypes.jl), by the way if you make a package containing those new gmp wrapper it would allow us to share this code)) then it makes sense not to support `T <: Any` and provide wrappers` <: RingElem` for efficiency (and ensuring that it is a ring).

What I suggest then is to separate `GenMPoly` and the polynomial type of `MultivariatePolynomials` but to provide very easy way to go back and forth.
We may also add conversions from the [univariate polynomial type](https://github.com/Keno/Polynomials.jl).

I understand that the modifications you mention may take time, no hurry. We will need `Nemo` to implement some functionality of the Sum of Squares package (see e.g. https://github.com/JuliaOpt/SumOfSquares.jl/issues/8) but for that we only need the `MPoly` branch to be merged and support for groebner basis computation (which is coming with `Singular.jl` if I understand correctly, or is there also a generic implementation ?).

There is also a sudden need for noncommutative variable (see https://github.com/blegat/MultivariatePolynomials.jl/issues/7) in MultivariatePolynomials.
I suggest the following (outside of Nemo)

* `Poly{T}`: univariate polynomial defined in Polynomials
* `Polynomial{T}`: commutative variable and noncommutative `T` defined in MultivariatePolynomials
* `NCPolynomial{T}`: non-commutative variable and noncommutative `T` in MultivariatePolynomials

with easy conversion with GenPoly and GenMPoly.

**Comment by wbhart** [comment]
On 16 December 2016 at 20:25, Benoît Legat <notifications@github.com> wrote:

> Thanks a lot for this detailed clarification!
>
> We can't define polynomials over T <: Any. Sometimes that doesn't even
> make sense, and if T is not associative even the generic algorithms you
> have in mind won't work.
>
> Indeed, allowing any T might lead to cases that do not make sense but when
> writing generic algorithms/libraries, we kind of need to take those risks.
> If the user provide a T that is not a Ring, he will be responsible :-P
>
Things actually need to belong to Nemo.RingElem before the generics in Nemo
will actually work on them. At the moment Nemo.GroupElem is more general
than Nemo.RingElem and certainly polynomials over the former don't make a
lot of sense (or at least you can't multiply such polynomials). But there
are generic algorithms for groups that we want to specialise for the case
where we actually have a ring or field. If we just assume that T <: Any is
a defacto ring type, all these group/ring algorithms stop working.

Also, if we change just this one requirement for polynomials to take Any,
then everyone else will expect us to do the same. For example, what about
matrices? Should they also accept Any?

Before long we have no way to distinguish cases for which there are much
faster algorithms. For example, a lot of algorithms over fields are O(n^3)
instead of O(n^4), or O(n^2) instead of O(n^3). So it's simply not possible
to put Any in place of Nemo.RingElem any more than it is possible to
replace Nemo.FieldElem with Nemo.RingElem.

I don't think there is any "most general" type that functions in a computer
algebra system should accept. Someone will always find something more
general, for which your algorithms that are supposed to take Any, will no
longer work!

Granted, we probably shouldn't be using the abstract type system to make
these distinctions in the first place, and should use traits or something
like that. But at least for now we can support the world of commutative
algebra relatively sanely.

> Of course, since you need it to implement the unsafe operation (I saw your
> post <https://groups.google.com/forum/#!topic/julia-dev/uqp7LziUEfY> on
> google groups explaining that you needed this to avoid to many allocations
> with BigInt (By the way, this post helped me a lot last year when needed to
> reimplement mpz et mpq wrappers for CDDLib
> <https://github.com/JuliaPolyhedra/CDDLib.jl/blob/master/src/mytype.jl>
> and LRSLib
> <https://github.com/JuliaPolyhedra/LRSLib.jl/blob/master/src/lrstypes.jl>,
> by the way if you make a package containing those new gmp wrapper it would
> allow us to share this code)) then it makes sense not to support T <: Any
> and provide wrappers<: RingElem for efficiency (and ensuring that it is a
> ring).
>
> What I suggest then is to separate GenMPoly and the polynomial type of
> MultivariatePolynomials but to provide very easy way to go back and forth.
> We may also add conversions from the univariate polynomial type
> <https://github.com/Keno/Polynomials.jl>.
>
> I understand that the modifications you mention may take time, no hurry.
> We will need Nemo to implement some functionality of the Sum of Squares
> package (see e.g. JuliaOpt/SumOfSquares.jl#8
> <https://github.com/JuliaOpt/SumOfSquares.jl/issues/8>) but for that we
> only need the MPoly branch to be merged and support for groebner basis
> computation (which is coming with Singular.jl if I understand correctly,
> or is there also a generic implementation ?).
>
We might implement a simple Buchberger in Nemo.jl for computing Groebner
bases. But this will be very slow and probably only a toy compared to what
is in Singular. The F4 algorithm requires fast linear algebra, and these
days GPU support or at least custom written assembly routines, etc., to get
good performance. It's extremely unlikely anyone will want to redo all of
that work in Julia. Singular has been under continuous development by a
team of people for about thirty years!

When computing Groebner bases of modules, Singular uses the same
representation for ideals and modules, and effectively just introduces
additional "variables" to handle module generators. This is not something
that is built into the Nemo MPoly type, and so there won't be any
easy/efficient way to compute Groebner bases of modules over Nemo
polynomials. If people want to do that sort of computation, they are
probably going to have to convert their polynomials to the Singular
polynomial type and then call the GB engine and convert back.

> There is also a sudden need for noncommutative variable (see blegat/
> MultivariatePolynomials.jl#7
> <https://github.com/blegat/MultivariatePolynomials.jl/issues/7>) in
> MultivariatePolynomials.
> I suggest the following (outside of Nemo)
>
>    - Poly{T}: univariate polynomial defined in Polynomials
>    - Polynomial{T}: commutative variable and noncommutative T defined in
>    MultivariatePolynomials
>    - NCPolynomial{T}: non-commutative variable and noncommutative T in
>    MultivariatePolynomials
>
> with easy conversion with GenPoly and GenMPoly
>

Sounds reasonable if you just want to use the Nemo generics over those
types.

Bill.

**Comment by wbhart** [comment]
In case it hasn't been mentioned to you yet, we have split Nemo into AbstractAlgebra.jl and Nemo.jl. The former has no C dependencies, and basically does what you and numerous others asked for.

We have not dealt with non-commutative coefficients yet, but I am currently working on it, as we require it for another project within our own collaboration, that we need to support.

Therefore, I will close this ticket as resolved.

**Comment by blegat** [comment]
Thanks for the update, we followed a similar direction by turning [MultivariatePolynomials](https://github.com/JuliaAlgebra/MultivariatePolynomials.jl) into an interface only and moving the implementation to [DynamicPolynomials](https://github.com/JuliaAlgebra/DynamicPolynomials.jl) allowing other implementation such that [TypedPolynomials](https://github.com/JuliaAlgebra/TypedPolynomials.jl/) to share the interface.
It seems that [MultivariatePolynomials](https://github.com/JuliaAlgebra/MultivariatePolynomials.jl) now have a goal similar to AbstractAlgebra.jl and it would be nice to see whether part of the interface can be shared in some way so that algorithms can be written that supports buth DynamicPolynomails, TypedPolynomials and Nemo but we can leave this discussion for another thread :)
