### ISSUE TITLE
lll_ctx not exported

### ISSUE THREAD

**Issue by dourouc05** [wbhart/Nemo.jl#76]
I just discovered this package, which completely fills one of my needs! I wasn't expecting something like this in Julia! 

When going through the documentation, I tried the following line: 

`B = lll(S(A), lll_ctx(0.99, 0.51))`

But I was faced with an unexpected error message: 

`ERROR: UndefVarError: lll_ctx not defined` 

The problem is quickly found: Nemo does not export `lll_ctx`. Either that fact should be clearly explained in the documentation, or the symbol should be exported, I think. I'd be in favour of the latter.

**Comment by wbhart** [comment]
Thanks, you are correct, it should be exported. I've created a PR to fix
this. It should get merged in the next day or so.

**Comment by dourouc05** [comment]
Great, thank you! 

BTW, what is blocking a PR like #63? Is it just a lack of test cases?

**Comment by wbhart** [comment]
Test cases would help that PR.

But there is also the question of what motivates such a conversion. Many
Julia matrix functions make invalid assumptions when they operate on exact
rings, so it's hard to come up with cases where you'd want to do such a
conversion. The Julia matrix functions are mainly for inexact, floating
point approximations and other types that model the reals or complex
numbers in some way.

**Comment by dourouc05** [comment]
My use case is to perform a lattice reduction, then to plug it into other software, where I need standard Julia matrices. Having such a functionality would help me write more readable code (not using loops to read the matrix element by element and to build another matrix, even if it is eased by comprehensions). 

If the conversion is not automatic (i.e. requires the user to write something like `Matrix(A)`), then I don't see any problem in having the conversion (automatic and transparent type conversions should not be possible, as it would be prone to the problems you point out).

**Comment by wbhart** [comment]
I guess that makes sense. The documentation would also have to be updated,
along with a warning "Warning: Julia matrices use a different data
structure than Nemo matrices. Conversion to Julia matrices is usually only
required for interfacing with other packages. It isn't necessary to convert
Nemo matrices to Julia matrices in order to manipulate them."

By the way, I wonder if that conversion function really should allow any
integer type. The data is only guaranteed to fit in a bignum, and we aren't
doing any checking in the implementation in that PR. Perhaps an inexact
exception should be thrown if the data doesn't fit in the requested type.

**Comment by dourouc05** [comment]
Both issues are now addressed (https://github.com/Nemocas/Nemo.jl/commit/23273bc50cb3b30b6fb0aa783e77eb5b7a514dcd and https://github.com/Nemocas/Nemo.jl/pull/202, for the records).
