### ISSUE TITLE
Provide binary dependecies

### ISSUE THREAD

**Issue by andreasnoack** [wbhart/Nemo.jl#89]
This is a really cool project but it takes forever to compile when doing a `Pkg.update()` so it would be great to look into the new options for shipping binary dependencies to speed things up.

**Comment by wbhart** [comment]
This is not the official GitHub repository. You want this one:

https://github.com/Nemocas/Nemo.jl

But I agree with this and it might happen one day. We were thinking of using Conda.jl, but haven't looked into the details.

I would be inclined to still build MPIR from source on Linux, since you get much better performance that way (in ways that especially matter to this project), but the rest could use prebuilt binaries.

We do of course use prebuilt binaries on Windows already.
